language: java
jdk:
- openjdk11
services:
- docker
before_install:
- docker build -t myApp/snapshot -f /ci/docker/dockerfile .
- docker run -d --name myApp
- docker ps -a
jobs:
  includes:
  - stage: test
    script: ./gradlew clean test
    after_success:
    - ./gradlew coveralls
  - stage: run locally and test healthcheck
    script: ./gradlew bootRun --args='--spring.profiles.active=dev'
notifications:
  slack:
    secure: Cos+hKPhu4kB5kaEVjGJxopg+yfmHZ46jcNToD1XkPxSotpZMbcCf07NA+FTmLVLqvWGv+FFh1IvlNlyUVHoiZ9bkJifah1v6B19vE7Xidqln2Erot8no7vEPZFCHHpFBaY8jzGPcsdPMr1yatZ7ygMQgXgGDsEk6rxzg+2ms0Oytp4QPRGumKq6qLlf+GaKNnobHTtjhtXWmn4CLxrNKJq62n1h/eH6J+St9LV7IFFm/8A3ZVVwZOKkNGouvkZsJr41sc9+mLEaLmNmN3Jr5iA2m4RduU3NE7i7y4BEdg+8n8JmHvjBlSwU/dcwVIh6/yEjomi3CQ/NsOCvDhiSXybJhmcpYpmrgALNerquec4XwW3+BPLDdj8CdhOsJPvJfO1EGpB0TPsgaeUTwKZftrHZmZj57G+Jlt4XdrXZWnNEsI99pIxrpKkjxjTGLWnPaDuJkEVi+EaPMLVTtO4oeZtUP1mDqiYrPyRzS3sOQd0tbveruggHLyrBEHgNI+mRoSLwrQquwFSGAR2S8dcvbBXl+BQmZzoFiiE0B8oKHFE1dw/GKMSa1QoTIjFCb6/aUoB7RP4El4nKxgDSxevujfKK/Lv5m6UAm/pNPw2+ebzyqRkgOY3lzcEBiKnpzIN/GW+v58lUIYLR7gY6oAxGpyijAsodw+a6/evfuoqAQEk=
branches:
  only:
  - main

